### ISSUE TITLE
ValLinkagePartialKey(generateEncoder)

### ISSUE THREAD

**Issue by jackfoxy** [thoth-org/Thoth.Json#45] opened 2019-11-24 22:16 UTC
This is only a problem when building in Visual Studio (seen with v16.3.10) and whatever mystery version of the SDK VS uses.

The problem does NOT exist at all when building with sdk 3.0.100

Thoth.Json 3.2 does not have this problem. 
Thoth.Json 3.4.1 throws the following build error:

```
Error	FS0193	The module/namespace 'Encode' from compilation unit 'Thoth.Json' did not contain the val 'ValLinkagePartialKey(generateEncoder)'	
```

**Comment by MangelMaxime** [comment] 2019-11-25 08:27
I have no idea what the problem is... and I can't repro it because I am using OSX and Linux right now.

I am enforcing the SDK version to be `3.0.100` see [global.json](https://github.com/thoth-org/Thoth.Json/blob/master/global.json) so I would say Visual Studio is doing something wrong.

Hello @cartermp, does this error ring something to you?

**Comment by cartermp** [comment] 2019-11-25 18:18
VS tooling respects `global.json` - any case of that not happening would be an issue with .NET SDK-style tooling (F# is irrelevant here).

**Comment by jackfoxy** [comment] 2019-11-25 20:37
I need to retest this to be sure I had the global.json present in the VS test

**Comment by cartermp** [comment] 2019-11-25 21:58
As I mentioned, this isn't an F# issue. I recommend filing a bug on the .NET project system.

**Comment by MangelMaxime** [comment] 2019-11-26 12:08
@jackfoxy Can you please open your issue in the .NET project system?

I am closing this issue because I don't think I can do something about it in this repo.

**Closed by MangelMaxime** 2019-11-26 12:08 UTC

**Comment by matthid** [comment] 2019-11-28 19:46
We see the same error in one of our projects after the upgrade... Interestingly another one works (which pretty much looks the same in terms of base layout, in fact it even references mostly the same code files)

**Comment by MangelMaxime** [comment] 2019-11-29 09:20
Seems like the problem is this one https://github.com/elmish/debugger/issues/38

**Comment by matthid** [comment] 2019-11-29 09:27
Maybe, but in the end the compiler message is not really helpful, and I assume that is just a wild guess?

**Comment by MangelMaxime** [comment] 2019-11-29 09:30
Yes, this is a wild guess but we don't really much more right now... If can unblock people I will take it :) because Thoth.Json 3.4.1 introduced several new features and people can need them especially if they use `Thoth.Fetch 2` in their project.

Can you please try using `Fable.Elmish.Debugger 3.1.0-beta-1`  and see if it fix the problem?

**Comment by jackfoxy** [comment] 2019-12-01 19:06
I upgraded to ```Fable.Elmish.Debugger 3.1.0-beta-1``` and ```Thoth.Json ~> 3``` and get a different error at compile time:
```
ERROR in ./.fable/Thoth.Json.3.4.1/Decode.fs
Module Error (from ./node_modules/fable-loader/index.js):
E:/GitRepos/NovaData/.fable/Thoth.Json.3.4.1/Decode.fs(1091,13): (1091,21) error FABLE: Cannot resolve System.Type.get_IsEnum
 @ ./src/Client/Client.fs 28:0-236 135:116-125 137:105-113 141:21-31 151:27-79 167:29-38 238:118-127 240:104-112 244:19-29 254:25-77 270:30-39
 @ ./src/Client/Client.fsproj
 @ multi ./src/Client/Client.fsproj
```
For the record, here are my complete server and client dependencies
```
group Server
    source https://api.nuget.org/v3/index.json
    framework: auto-detect
    storage: none

    nuget FSharp.Core 
    nuget FSharp.Data
    nuget Fable.Core ~> 3
    nuget Saturn ~> 0.10
    nuget Thoth.Json ~> 3
    nuget Thoth.Json.Giraffe ~> 2

group Client
    source https://api.nuget.org/v3/index.json
    framework: auto-detect
    storage: none

    nuget FSharp.Core

    nuget Fable.Core ~> 3
    nuget Fable.Elmish ~> 3
    nuget Fable.Elmish.Debugger 3.1.0-beta-1 
    nuget Fable.Elmish.React  ~> 3
    nuget Fable.Elmish.HMR ~> 4
    nuget Fable.Fetch ~> 2
    nuget Fable.React ~> 5
    nuget Fulma ~> 2
    nuget Fable.Recharts ~> 1
    nuget Fable.FontAwesome ~> 2
    nuget Fable.FontAwesome.Free ~> 2

    clitool dotnet-fable 2.0.11
	nuget Thoth.Fetch ~> 1
	nuget Thoth.Json ~> 3
```

**Comment by jackfoxy** [comment] 2019-12-01 19:16
I should also mention my project is locked to build with SDK 3.0.100

**Comment by MangelMaxime** [comment] 2020-01-06 15:59
Hello @jackfoxy sorry for the late answer, 

can you please check that you are using the latest version of  `fable-compiler` (npm deps). We supported more API reflection some versions ago which was for Enum reflection.

**Comment by rfrerebe** [comment] 2020-01-09 12:13
Hello,

I can confirm that using latest fable-compiler (2.4.12) and pinning Fable.Elmish.Debugger to 3.1.0-beta-1 does fix this issue

**Comment by jackfoxy** [comment] 2020-01-12 22:20
Yeah, I don't think this is an issue anymore.

**Comment by OnurGumus** [comment] 2020-04-07 08:48
I actually hit to this issue for different reason.  For testing purposes, I was trying to run Fable's elmish loop in a console app and hit to this problem.

**Comment by MangelMaxime** [comment] 2020-04-07 09:08
@OnurGumus You need to look at your dependencies list and check that all of them has been build with the latest version of Thoth.Json.Net.

That's how we fixed the problem in the rest of the ecosystem. Sorry I don't know any other way to fix this issue...

**Comment by OnurGumus** [comment] 2020-04-07 11:29
@MangelMaxime, the server side component was already using **Thoth.Json.Net 4.0** and still I was getting the error. What worked for me is to downgrade **Thoth.Json** from **4.0** to **3.1,** then I am getting no error. Could it be the issue revamped with **Thoth.Json 4.0**?

**Comment by MangelMaxime** [comment] 2020-04-07 11:38
@OnurGumus Are you sure you don't have a dependency which depends on Thoth.Json.Net?

Could you please share your dependency file?

**Comment by OnurGumus** [comment] 2020-04-07 11:40
```
Version 5.241.2

group Server
    source https://api.nuget.org/v3/index.json
    source https://www.myget.org/F/resoptima/api/v3/index.json username: "%MYGET_USER%" password: "%MYGET_READ_APIKEY%"

    framework: netcoreapp3.1
    storage: none

    nuget Giraffe
    nuget Elmish.Bridge.Giraffe ~> 3
    nuget Thoth.Json.Giraffe
    nuget Thoth.Json >= 4.0
    nuget Expecto < 9.0 //9.0 breaks YoloDev.Expecto.TestSdk
    nuget FSharp.Core >= 4.0
    nuget Microsoft.NET.Test.Sdk >= 16.0
    nuget YoloDev.Expecto.TestSdk
    nuget altcover
    nuget canopy
    nuget selenium.webdriver.chromedriver
    nuget TickSpec prerelease
    nuget Google.Protobuf
    nuget Grpc
    nuget Grpc.Tools
    nuget Serilog
    nuget Destructurama.FSharp prerelease
    nuget Serilog.Sinks.Console
    nuget Irma.Infill.Client >= 0.0.1-alpha.1
    nuget Resoptima.Irma.Ensemble.Client  >= 0.1.13

group Client
    source https://api.nuget.org/v3/index.json
    framework: netstandard2.0
    storage: none

    nuget Fable.Core ~> 3
    nuget Fable.Elmish ~> 3
    //for both server and client side testing
    nuget Thoth.Json 3.1
    nuget Fable.Elmish.Debugger ~> 3
    nuget Fable.Elmish.HMR ~> 4
    nuget Fable.Elmish.React ~> 3
    nuget Thoth.Fetch ~> 1
    nuget Fable.React ~> 5
    nuget Elmish.Bridge.Client ~> 3
    nuget Fulma ~> 2
    nuget Fable.FontAwesome.Free ~> 2
    nuget Feliz
    nuget Feliz.Bulma
    nuget Zanaptak.TypedCssClasses
```

**Comment by OnurGumus** [comment] 2020-04-07 11:42
@MangelMaxime basically I have test project both references client and server and failing with above error. If I put the below constraint
```
//for both server and client side testing
    nuget Thoth.Json 3.1
```
It works fine. If I remove 3.1 contraint then it uses 4.0 and causes the error.

**Comment by MangelMaxime** [comment] 2020-04-07 14:22
Hum, but do you have the errors coming from Thoth.Json or Thoth.Json.Net ?

I think the problem is that you put a constraint on some dependencies and not others. I suppose this is also because most of my project requires others dependencies to be of version X at least but never put a limit to the top one.

In your case, I think the problem is coming from `Thoth.Fetch ~> 1` when it's `Thoth.Fetch v2` which support Thoth.Json v4. [Changelog](https://github.com/thoth-org/Thoth.Fetch/blob/master/CHANGELOG.md)

**Comment by OnurGumus** [comment] 2020-04-07 16:02
I removed all the constraints, did paket update and still same error . You can see the diff file for paket.lock:

![image](https://user-images.githubusercontent.com/4114592/78692218-d8572100-78f9-11ea-846a-7f3c11372b80.png)

**Comment by MangelMaxime** [comment] 2020-04-07 18:30
@OnurGumus Can you please test with Elmish.Debugger 3.2.0-beta-1?

**Comment by OnurGumus** [comment] 2020-04-07 18:52
@MangelMaxime Yay, that worked! Thanks a lot.

**Comment by MangelMaxime** [comment] 2020-04-07 19:00
@OnurGumus Thank you for the confirmation.

I released it as a stable version.
